

DNAstr = "CGCAAACGCCAGCGAAAGTATGAGAACACGAAATATATGGGGGCACTTGCTGTCCTAATGTGTACGGAA$
countA, countC, countG, countT = 0,0,0,0
for i in range(0,DNAstr.len)
    if DNAstr[i] == 'A'
        countA++
    if DNAstr[i] == 'C'
        countC++
    if DNAstr[i] == 'G'
        countG++
    if DNAstr[i] == 'T'
        countT++
print countA + ' ' + countC + ' ' + countG + ' ' + countT

DNAstr = "CGCAAACGCCAGCGAAAGTATGAGAACACGAAATATATGGGGGCACTTGCTGTCCTAATGTGTACGGAACTCGATCTGTAGTCCCTTCAACAGCTTTCGTAGTGAAATGATTCCCAAGTTTATCTGTCACCGTGTCGTCGTTAAGGCGTCGCGGGTCGAACGGGTGTCCGCCTTGAGATGTCTCAAGGTCACTCAGGGGGCGTACAGAAATTAAGCTGTATCTGCACATCGACCGGATTTAGACTGCAGAGACAACTGCCCTTTGTTGCTATCAACATCGGGTTTAAACTAGAGTGTCTTCTGCTTGCGGATGTTCTGACGGGGAACCAGCGATTCAAGGCAAATTGCGAACTATGCAAGGAGGATTACTAAGGAGAAAATGCAGGCTGTGTATAGGCAACGAGTCAATTACTCTCGCGAATTCACATAACGATCACGAACACCTGGGGTCTGTGTCCGTGGCGGTCTATAATCCCCTGGATCCAGCTTGGTAAAGTTGTCCTAAGCCAAATGCGACTATGCTCCTGCAGGCTGGACCATAGAGTCATCGTCGCCTAAGGGCTTAACTAATCGTAGGCGACGTGGTATCCCCATTCCCGAAGGGTGCGGTGTTCCGTGGCTGATCTAATGCGTTGAGACTGTCAAGTGTTGAGCTAAAGCGTTGAGTTCCTTAGCGTATGTTAACTGTGCGTTCCGGGCGGGACAACGGTATAGATTCTTGACTTTAGGTGTGGGCAGGGGCTTCTAACCTTTGCGTCTGTCACTCAGGTTCTTCCCAAAACTGCTACCTCATCATATCCTGGTTTGCTCTAAGACGTATTGC"
countA, countC, countG, countT = 0,0,0,0
for i in range(0,DNAstr.len)
    if DNAstr[i] == 'A'
        countA++
    if DNAstr[i] == 'C'
        countC++
    if DNAstr[i] == 'G'
        countG++
    if DNAstr[i] == 'T'
        countT++
print countA + ' ' + countC + ' ' + countG + ' ' + countT

       
